
	// UserManager.idl : IDL source for UserManager.exe
//
// This file will be processed by the MIDL tool to
// produce the type library (UserManager.tlb) and marshalling code.
import "oaidl.idl";
import "ocidl.idl";
[
	uuid(C95DC84D-6183-11D2-A57C-00A0248552AD),
	version(1.0),
	helpstring("UserManager 1.0 Type Library")
]
library UserManagerLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};

	