///////////////////////////////////////////////////////////////////////////////
// DBProtocol.h - DB Server Protocol Define
//

#ifndef _DBPROTOCOL_H_
#define _DBPROTOCOL_H_

#define DBPROTOCOL		(WORD)(0x9000)

#define DB_CREATETABLE_REQ	(DBPROTOCOL + 0)
#define DB_CREATETABLE_ACK	(DBPROTOCOL + 1)
#define DB_OPENTABLE_REQ	(DBPROTOCOL + 2)
#define DB_OPENTABLE_ACK	(DBPROTOCOL + 3)
#define DB_CLOSETABLE_REQ	(DBPROTOCOL + 4)
#define DB_CLOSETABLE_ACK	(DBPROTOCOL + 5)
#define DB_INSERTRECORD_REQ	(DBPROTOCOL + 6)
#define DB_INSERTRECORD_ACK	(DBPROTOCOL + 7)
#define DB_DELETERECORD_REQ	(DBPROTOCOL + 8)
#define DB_DELETERECORD_ACK	(DBPROTOCOL + 9)
#define DB_GETRECORD_REQ	(DBPROTOCOL + 10)
#define DB_GETRECORD_ACK	(DBPROTOCOL + 11)
#define DB_SETRECORD_REQ	(DBPROTOCOL + 12)
#define DB_SETRECORD_ACK	(DBPROTOCOL + 13)
#define DB_NUMRECORD_REQ	(DBPROTOCOL + 14)
#define DB_NUMRECORD_ACK	(DBPROTOCOL + 15)

#define FIELD_TYPE_BYTE		(BYTE)0
#define FIELD_TYPE_WORD		(BYTE)1
#define FIELD_TYPE_DWORD	(BYTE)2
#define FIELD_TYPE_STRING	(BYTE)3



#endif//_DBPROTOCOL_H_