//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ServiceManager.rc
//
#define IDC_BUTTON_REG                  3
#define ID_FILE_VIEW                    3
#define IDD_ABOUTBOX                    100
#define CG_IDD_VIEWBAR                  102
#define CG_ID_VIEW_VIEWBAR              103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_SERVTYPE                    129
#define IDD_SERVICE                     129
#define IDB_TREEIMAGE                   130
#define IDD_USER                        130
#define IDD_SERVER                      133
#define IDD_SELSERVICE                  134
#define IDD_SESSION                     135
#define IDD_LOGIN                       136
#define IDD_SELSERVER                   137
#define IDD_CONFIGUM                    139
#define IDD_CONFIGFM                    140
#define IDD_CONFIGSM                    141
#define IDD_CONFIGDB                    142
#define IDD_CONFIGGS                    143
#define IDD_ADDFILE                     146
#define IDD_DELFILE                     148
#define IDD_SETVERSION                  149
#define IDD_LOG                         150
#define IDD_SERIAL                      152
#define IDD_FINDUSER                    153
#define IDD_REGVALUE                    154
#define IDD_FINDSERIAL                  155
#define IDD_CONVSERIAL                  156
#define IDD_NEWSERIAL                   157
#define IDD_BANK                        159
#define IDD_BANKSERIAL                  161
#define IDD_CLIENT                      162
#define IDD_FINDCLIENT                  164
#define IDD_CLIENTLIST                  166
#define IDD_FINDBANK                    167
#define IDD_BADID                       169
#define IDD_CLIENT_PAY                  170
#define IDD_PAYDETAIL                   175
#define IDB_LOGO                        177
#define IDD_PRINTBILL_DLG               178
#define IDD_DELETE_CLIENT               181
#define IDD_PRINT_ADDR                  182
#define IDD_BILLDLG                     184
#define IDD_CLIENT_SELECT               185
#define IDD_NOTICE_SET                  186
#define IDD_FILE_COMPRESS               187
#define IDC_EDIT_NAME                   1000
#define IDC_EDIT_ADDR                   1001
#define IDC_EDIT_REG_USERID             1001
#define IDC_BUTTON_ADDIPADDR            1002
#define IDC_EDIT_REG_PASSWD             1002
#define IDC_BUTTON_SETDEFAULT           1003
#define IDC_EDIT_GS_NAME                1003
#define IDC_LIST_ADDR                   1004
#define IDC_EDIT_REG_NAME               1004
#define IDC_EDIT_REG_SOCNUM1            1005
#define IDC_EDIT_REG_SOCNUM2            1006
#define IDC_EDIT_SM_NAME                1007
#define IDC_EDIT_GS_PORT                1007
#define IDC_EDIT_REG_TELNO              1007
#define IDC_EDIT_GS_CAPACITY            1008
#define IDC_EDIT_REG_EMAIL              1008
#define IDC_EDIT_GS_TIMEOUT             1009
#define IDC_EDIT_SERIAL1                1009
#define IDC_EDIT_REG_ADDRESS            1009
#define IDC_EDIT_REG_ADDRESS1           1009
#define IDC_EDIT_GS_TIMER               1010
#define IDC_EDIT_SERIAL2                1010
#define IDC_EDIT_REG_ADDRESS2           1010
#define IDC_EDIT_GS_ID                  1011
#define IDC_COMBO_SERVER                1012
#define IDC_COMBO_GS_ADDR               1013
#define IDC_LIST_SERVICE                1014
#define IDC_EDIT_GAMEID                 1015
#define IDC_LIST_SERVER                 1016
#define IDC_EDIT_PASSWD                 1017
#define IDC_BUTTON_GS_ADD               1031
#define IDC_BUTTON_GS_DEL               1032
#define IDC_COMBO_UM_SERVER             1033
#define IDC_BUTTON_GS_UPDATE            1033
#define IDC_COMBO_UM_ADDR               1034
#define IDC_BUTTON_GS_REFRESH           1034
#define IDC_EDIT_UM_PORT                1035
#define IDC_BUTTON_GS_DEFAULT           1035
#define IDC_EDIT_UM_CAPACITY            1036
#define IDC_COMBO_FM_SERVER             1045
#define IDC_COMBO_FM_ADDR               1046
#define IDC_EDIT_FM_PORT                1047
#define IDC_EDIT_FM_PATH                1048
#define IDC_COMBO_DB_SERVER             1050
#define IDC_COMBO_DB_ADDR               1051
#define IDC_EDIT_DB_PORT                1052
#define IDC_EDIT_DB_PATH                1053
#define IDC_EDIT_UM_MODULE              1054
#define IDC_EDIT_FM_MODULE              1055
#define IDC_EDIT_DB_MODULE              1056
#define IDC_EDIT_FM_BUFFER              1056
#define IDC_EDIT_SM_MODULE              1057
#define IDC_EDIT_FM_HOLD                1057
#define IDC_EDIT_GS_MODULE              1059
#define IDC_COMBO_SM_SERVER             1060
#define IDC_COMBO_SM_ADDR               1061
#define IDC_EDIT_SM_PORT                1062
#define IDC_EDIT_SM_TIMEOUT             1063
#define IDC_EDIT_SM_CAPACITY            1064
#define IDC_RADIO_SM_PAY                1065
#define IDC_COMBO_GS_SERVER             1066
#define IDC_RADIO_SM_PAY2               1066
#define IDC_EDIT_DB_CAPACITY            1068
#define IDC_EDIT_FM_CAPACITY            1070
#define IDC_LIST_GS                     1073
#define IDC_LIST_SM                     1074
#define IDC_BUTTON_SM_ADD               1075
#define IDC_BUTTON_SM_UPDATE            1076
#define IDC_BUTTON_SM_DEL               1077
#define IDC_EDIT_SM_ID                  1078
#define IDC_BUTTON_SM_REFRESH           1078
#define IDC_LIST_FILE                   1079
#define IDC_BUTTON_ADDFILE              1080
#define IDC_LIST_DEL                    1080
#define IDC_BUTTON_DELFILE              1081
#define IDC_CHECK_COMP                  1082
#define IDC_BUTTON_RESTORE              1082
#define IDC_EDIT_VER                    1083
#define IDC_EDIT_PATH                   1084
#define IDC_BUTTON_ADDALL               1085
#define IDC_COMBO_STARTMONTH            1088
#define IDC_COMBO_STARTYEAR             1089
#define IDC_COMBO_STARTDAY              1090
#define IDC_COMBO_ENDMONTH              1091
#define IDC_COMBO_ENDYEAR               1092
#define IDC_COMBO_ENDDAY                1093
#define IDC_COMBO_SERVICE               1094
#define IDC_CHECK_ALLSERVICE            1095
#define IDC_EDIT_USERID                 1096
#define IDC_EDIT_SERIALNO               1097
#define IDC_EDIT_REGYEAR                1098
#define IDC_EDIT_ENTERNAME              1098
#define IDC_EDIT_REGMONTH               1099
#define IDC_EDIT_REGDAY                 1100
#define IDC_EDIT_BANK                   1101
#define IDC_EDIT_LOGYEAR                1101
#define IDC_EDIT_PAYNAME                1102
#define IDC_EDIT_LOGMONTH               1102
#define IDC_EDIT_PRICE                  1103
#define IDC_EDIT_LOGDAY                 1103
#define IDC_RADIO_TYPE                  1104
#define IDC_RADIO2                      1105
#define IDC_RADIO_TYPEGAME              1105
#define IDC_EDIT_STARTYEAR              1106
#define IDC_EDIT_STARTMONTH             1107
#define IDC_EDIT_VALUE                  1108
#define IDC_EDIT_STARTDAY               1108
#define IDC_EDIT_ENDYEAR                1109
#define IDC_EDIT_PAYYEAR                1110
#define IDC_RADIO_TYPE2                 1110
#define IDC_EDIT_PAYMONTH               1111
#define IDC_EDIT_SERIAL                 1111
#define IDC_EDIT_PAYDAY                 1112
#define IDC_EDIT_ENDMONTH               1113
#define IDC_EDIT_SERIALPASSWD           1114
#define IDC_EDIT_ENDDAY                 1115
#define IDC_EDIT_RECYEAR                1116
#define IDC_EDIT_RECMONTH               1117
#define IDC_EDIT_RECDAY                 1118
#define IDC_EDIT_MAXREGUSER             1121
#define IDC_SPIN_MAXREGUSER             1124
#define IDC_EDIT_CURREG                 1125
#define IDC_EDIT_CURREGUSER             1125
#define IDC_SPIN1                       1126
#define IDC_SPIN_CURREGUSER             1126
#define IDC_EDIT_VALIDDAY               1128
#define IDC_SPIN_VALIDDAY               1129
#define IDC_COMBO_BANK                  1131
#define IDC_EDIT_MONEY                  1133
#define IDC_EDIT_OPER                   1134
#define IDC_EDIT_BANKYEAR               1136
#define IDC_EDIT_COMMENT                1137
#define IDC_EDIT_NUMSERIAL              1138
#define IDC_EDIT_BANKMONTH              1140
#define IDC_EDIT_BANKDAY                1141
#define IDC_BUTTON_BANK                 1142
#define IDC_BUTTON_SERIAL               1143
#define IDC_LIST_SERIAL                 1148
#define IDC_DATETIMEPICKER_START        1149
#define IDC_DATETIMEPICKER_END          1150
#define IDC_DATETIMEPICKER_BANKDATE     1151
#define IDC_COMBO_BANKTYPE              1152
#define IDC_EDIT_SOC1                   1153
#define IDC_EDIT_CLIENT_REGNO1          1154
#define IDC_EDIT_CLIENT_ZIP1            1155
#define IDC_EDIT_CLIENT                 1156
#define IDC_EDIT_CLIENT_ZIP2            1156
#define IDC_BUTTON_FINDCLIENT           1157
#define IDC_COMBO_BANKPROC              1158
#define IDC_EDIT_BANKTEL                1159
#define IDC_EDIT_CLIENT_REGNO2          1161
#define IDC_EDIT_CLIENT_REGNO3          1162
#define IDC_EDIT_CLIENT_NAME            1163
#define IDC_EDIT_CLIENT_HOST            1164
#define IDC_EDIT_CLIENT_ADDRESS         1165
#define IDC_EDIT_CLIENT_TYPE            1166
#define IDC_EDIT_CLIENT_KIND            1167
#define IDC_COMBO_CLIENT_LOC            1168
#define IDC_COMBO_CLIENT_LINE           1170
#define IDC_EDIT_CLIENT_TELNO           1171
#define IDC_EDIT_CLIENT_NUMPC           1172
#define IDC_EDIT_CLIENT_EMAIL           1173
#define IDC_EDIT_SOC2                   1174
#define IDC_DATETIMEPICKER_CLIENT_REGDATE 1175
#define IDC_EDIT_CLIENT_ID              1176
#define IDC_BUTTON_SEARCHBANK           1178
#define IDC_BUTTON_NEWCLIENT            1179
#define IDC_EDIT_SEARCHNAME             1181
#define IDC_DATETIMEPICKER_SEARCHFROM   1182
#define IDC_EDIT_SEARCHTEL              1182
#define IDC_DATETIMEPICKER_SEARCHTO     1183
#define IDC_EDIT_SEARCHHOST             1183
#define IDC_COMBO_SEARCHLOC             1188
#define IDC_LIST_CLIENT                 1189
#define IDC_BUTTON_SEARCH               1190
#define IDC_BUTTON_CLIENT               1191
#define IDC_RADIO_MONTH                 1192
#define IDC_RADIO_TIME                  1193
#define IDC_DATETIMEPICKER_SEARCHSTART  1195
#define IDC_DATETIMEPICKER_SEARCHEND    1196
#define IDC_DATETIMEPICKER_INTERVAL_TO  1196
#define IDC_EDIT_BADID_DUE              1197
#define IDC_EDIT_BADID_COMMENT          1198
#define IDC_DATETIMEPICKER_REG          1200
#define IDC_DATETIMEPICKER_LOG          1201
#define IDC_FROM_YEAR                   1201
#define IDC_TO_YEAR                     1202
#define IDC_CLIENT_LIST                 1208
#define IDC_FROM_MONTH                  1213
#define IDC_TO_MONTH                    1214
#define IDC_COMBO1                      1216
#define IDC_FILE_VERSION                1216
#define IDC_DETAIL_LIST                 1217
#define IDC_CLIENT_NAME                 1218
#define IDC_TOTAL_COST                  1219
#define IDC_DELEY_PAY                   1220
#define IDC_DATETIME_INTERVAL_DEAD      1221
#define IDC_DATETIMEPICKER_INTERVAL_FROM 1222
#define IDC_PRINT_TAX                   1224
#define IDC_OPER                        1231
#define IDC_REASION                     1232
#define IDC_BILL_DATE                   1232
#define IDC_COPY_SERIAL                 1233
#define IDC_BUTTON_CLIENTSEARCH         1236
#define IDC_EDIT_IPNUMBER               1238
#define IDC_EDIT_VALIDTIME              1239
#define IDC_SPIN_VALIDTIME              1240
#define IDC_EDIT_IPSTART                1241
#define IDC_EDIT_IPEND                  1242
#define IDC_RADIO_TYPECUSTOM1           1243
#define IDC_EDIT_CUSTOM1DAY             1244
#define IDC_SPIN_CUSTOM1DAY             1245
#define IDC_NOTICE_VALUE                1246
#define IDC_NOTICE_MESSAGE              1247
#define IDC_EDIT_CLIENT_IPADDRESS       1248
#define IDC_EDIT_CLIENT_ETC             1249
#define IDC_RADIO_EXTENSIONUSER         1250
#define IDC_RADIO_EXTENSION             1250
#define IDC_CHECK_CLOSE                 1251
#define IDC_DIR                         1251
#define IDC_DIR_SEARCH                  1252
#define ID_COMPRESS                     1253
#define IDC_EDIT_SEARCHREGNO1           1254
#define IDC_FILE_LIST                   1254
#define IDC_EDIT_SEARCHREGNO2           1255
#define IDC_EDIT_SEARCHREGNO3           1256
#define IDC_ZIP_PROGRESS                1257
#define IDC_DATETIMEPICKER_SEARCHDATE   1258
#define IDC_ZIP_STATIC                  1258
#define ID_CONFIG_ADDSERVER             32771
#define ID_CONFIG_ADDSERVICE            32772
#define ID_CONFIG_DELSERVER             32773
#define ID_CONFIG_DELSERVICE            32774
#define ID_CONFIG_CONNECTSERVER         32775
#define ID_CONFIG_ADDSESSION            32776
#define ID_CONFIG_ADDUM                 32777
#define ID_CONFIG_ADDFM                 32778
#define ID_CONFIG_ADDGS                 32779
#define ID_CONFIG_ADDDB                 32780
#define ID_CONFIG_SERVICE               32782
#define ID_CONTROL_START                32783
#define ID_CONTROL_STOP                 32784
#define ID_CONTROL_PAUSE                32785
#define ID_CONTROL_CONTINUE             32786
#define ID_CONFIG_SETVERSION            32794
#define ID_CONFIG_ADDFILE               32795
#define ID_FILE_DELFILE                 32796
#define ID_CONFIG_UPDATEFILE            32797
#define ID_CONFIG_DELFILE               32798
#define ID_CONFIG_FILECOMP              32799
#define ID_SEARCH_LOG                   32800
#define ID_CONFIG_SERVER                32801
#define ID_SERVER_ADD                   32802
#define ID_SERVER_DEL                   32803
#define ID_SERVER_CONNECT               32804
#define ID_SERVER_CONFIG                32805
#define ID_SERVICE_CONFIG               32807
#define ID_SERVICE_DEL                  32808
#define ID_VERSION_SET                  32809
#define ID_VERSION_ADD                  32810
#define ID_VERSION_DEL                  32811
#define ID_VERSION_CONFIG               32812
#define ID_VERSION_COMPRESS             32813
#define ID_MANAGE_LOG                   32814
#define ID_MANAGE_NEWSERIAL             32815
#define ID_MANAGE_SEARCHSERIAL          32816
#define ID_MANAGE_FINDUSER              32817
#define ID_SERVICE_VALUE                32818
#define ID_MANAGE_UPDATESERIAL          32819
#define ID_MANAGE_CONVSERIAL            32820
#define ID_MANAGE_CONUSER               32823
#define ID_CONTROL_STOPALL              32824
#define ID_CONTROL_STARTALL             32825
#define ID_MANAGE_BANK                  32826
#define ID_MANAGE_DISCONNECT            32827
#define ID_SERVICE_GETVALUE             32828
#define ID_VIEW_SERIAL                  32829
#define ID_VIEW_LOG                     32830
#define ID_VIEW_BANK                    32831
#define ID_CLIENT_NEW                   32833
#define ID_CLIENT_SEARCH                32834
#define ID_MANAGE_SERIALUSE             32835
#define ID_LOG_SEARCH                   32836
#define ID_MANAGE_BADID                 32837
#define ID_MANAGE_BADIDLIST             32838
#define ID_MANAGE_CLIENTPAY             32839
#define ID_MANAGE_CLIENTLOG             32840
#define ID_FILE_SAVELOG                 32841
#define ID_MANAGE_CURRENTUSER           32842
#define ID_MANAGE_CLIENTPAYLIST         32843
#define ID_MANAGE_PRINTBILL             32844
#define ID_PRINT                        32847
#define ID_LIST_PRINT                   32850
#define ID_LIST_PRINT_PREVIEW           32851
#define ID_SAVE_LIST                    32852
#define ID_PRINT_ADDRESS                32854
#define ID_FINISHDAY                    32855
#define ID_COUNT_REFRESH                32856
#define ID_CLIENT_BANK                  32857
#define ID_PRINT_BANK                   32858
#define ID_NOTICE_SET                   32859
#define ID_NOTICE_SESSION               32860
#define ID_FILE_DIR_COMPRESS            32861
#define IDS_TREE_SERVER                 61446
#define IDS_TREE_IPADDR                 61447
#define IDS_TREE_SERVICE                61448
#define IDS_MSG_INSTALLFAIL             61449
#define IDS_MSG_NULL                    61450
#define IDS_MSG_LOGINFAIL               61451
#define IDS_TITLE_CONFIG                61452
#define IDS_TREE_SERVICE_PORT           61453
#define IDS_TREE_SERVICE_CAPACITY       61454
#define IDS_TREE_SERVICE_TIMEOUTS       61455
#define IDS_TREE_SERVICE_ADDR           61456
#define IDS_TREE_SERVICE_TIMER          61457
#define IDS_TREE_SERVICE_TIMEOUTNONE    61458
#define IDS_TREE_SERVICE_TIMERNONE      61459
#define IDS_MSG_INSTALLDB               61460
#define IDS_MSG_INSTALLFM               61461
#define IDS_MSG_STARTFAIL               61462
#define IDS_MSG_STOPFAIL                61463
#define IDS_MSG_CONTINUEFAIL            61464
#define IDS_MSG_PAUSEFAIL               61465
#define IDS_MSG_INSTALLUM               61466
#define IDS_MSG_NOTINSTALLUM            61467
#define IDS_MSG_NOTINSTALLFM            61468
#define IDS_MSG_NOTINSTALLSM            61469
#define IDS_NOTUPDATESERVICE            61470
#define IDS_TREE_UM                     61471
#define IDS_TREE_FM                     61472
#define IDS_TREE_DB                     61473
#define IDS_TREE_SM                     61474
#define IDS_TREE_GS                     61475
#define IDS_TREE_CONFIG_SERVER          61476
#define IDS_TREE_DB_DBPATH              61477
#define IDS_TREE_FM_SRCPATH             61478
#define IDS_TREE_SM_CAPACITY            61479
#define IDS_TREE_SM_PAY                 61480
#define IDS_TREE_SM_FREE                61481
#define IDS_TREE_SM_ID                  61482
#define IDS_TREE_GS_ID                  61483
#define IDS_TREE_VERSION                61484
#define IDS_TREE_UM_FMADDR              61485
#define IDS_TREE_UM_DBADDR              61486
#define IDS_TREE_UM_GSADDR              61487
#define IDS_TREE_FM_DBADDR              61488
#define IDS_TREE_FM_BUFFER              61489
#define IDS_TREE_VER_NUMFILE            61490
#define IDS_TREE_VER_CURRENT            61491
#define IDS_TREE_VER_VERSION            61492
#define IDS_TREE_VER_FILECOMP           61493
#define IDS_MSG_SEARCHRANGE             61494
#define IDS_REASON_NORMAL               61495
#define IDS_REASON_DUPLICATE            61496
#define IDS_REASON_CANCEL               61497
#define IDS_REASON_CLIENT               61498
#define IDS_REASON_TIMEOUT              61499
#define IDS_REASON_LINK                 61500
#define IDS_REASON_SESSION              61501
#define IDS_MSG_USERFINDFAIL            61502
#define IDS_MSG_USERSETFAIL             61503
#define IDS_MSG_USERSETSUCC             61504
#define IDS_ERR_INVALIDSERIAL           61505
#define IDS_FMT_QUERYSERIAL             61506
#define IDS_FMT_NEWSERIAL               61507
#define IDS_FMT_SERIALLOG               61508
#define IDS_MSG_FINDSERIALFAIL          61509
#define IDS_MSG_NEWSERIALFAIL           61510
#define IDS_MSG_INSERTFILEFAIL          61511
#define IDS_MSG_DUPFILE                 61512
#define IDS_MSG_DELFILEFAIL             61513
#define IDS_FMT_COUNT                   61514
#define IDS_FMT_CONUSERSERIAL           61515
#define IDS_FMT_CONUSER                 61516
#define IDS_MSG_CONUSERNOTFOUND         61517
#define IDS_TITLE_COUNTALL              61518
#define IDS_MSG_ACCESSNOTPERMITTED      61519
#define IDS_MSG_UPDATESERIALFAIL        61520
#define IDS_MSG_UPDATEBANKFAIL          61521
#define IDS_MSG_BANKSERIALFAIL          61522
#define IDS_FMT_COUNTSESSION            61523
#define IDS_FMT_VALUESTRING             61524
#define IDS_FMT_VALUEINT                61525
#define IDS_MSG_NEWCLIENTFAIL           61526
#define IDS_MSG_UPDATECLIENTFAIL        61527
#define IDS_MSG_SEARCHCLIENTFAIL        61528
#define IDS_MSG_CLIENTSERIALFAIL        61529
#define IDS_MSG_SEARCHLOGFAIL           61530
#define IDS_MSG_ADDBADID                61531
#define IDS_ERR_DBOPEN                  61532
#define IDS_ERR_BADIDEXIST              61533
#define IDS_MSG_RETURNBADID             61534
#define IDS_TREE_COUNT                  61535
#define IDS_MSG_SERIALFAIL              61535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32862
#define _APS_NEXT_CONTROL_VALUE         1259
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
