# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
CONFIG += staticlib

include(../public.pri)

TARGET = Zip
DESTDIR = ./lib/$(Platform)/$(Configuration)
DEFINES += ZLIB_DLL

PRECOMPILED_HEADER = stdafx.h

INCLUDEPATH += ./zlib ./sources ./include . ../libs/zip/include

HEADERS += ./include/*.h
SOURCES += ./sources/*.cpp

