# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
CONFIG += staticlib release

include(../public.pri)

TARGET = Zip
DESTDIR = ./lib/$(Platform)/$(Configuration)
DEFINES += ZLIB_DLL

PRECOMPILED_HEADER = stdafx.h

INCLUDEPATH += ./zlib ./sources ./include .

HEADERS += ./sources/*.h ./include/*.h
SOURCES += ./sources/*.cpp

